/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/**
 * Storage and cache config the `connect` URI can't carry. All fields are
 * optional; omit for local / `memory://` / ambient-credential S3 with no
 * disk cache.
 */
export interface ConnectOptions {
  /** S3-compatible endpoint; requires `region`, `accessKey`, `secretKey`. */
  endpoint?: string
  region?: string
  accessKey?: string
  secretKey?: string
  /** Local disk-cache directory for remote-backed tables. */
  cacheDir?: string
  /** Disk-cache budget in bytes (a JS number; up to 2^53). */
  cacheBudgetBytes?: number
  /**
   * Cold-miss strategy: `"hybrid_with_prefetch"` | `"range_only"` |
   * `"lazy_foreground_with_background_fill"`.
   */
  coldFetchMode?: string
}
/** Tuning for `optimize`; all fields optional (omitted ⇒ engine default). */
export interface OptimizeOptions {
  /** Build-time memory budget, in MB. */
  maxMemoryMb?: number
  /** Only compact superfiles below this fill percent (0–100). */
  minFillPercent?: number
  /** Target merged-superfile size, in MB. */
  targetSuperfileSizeMb?: number
}
/** Row counts from an `update` / `delete`. */
export interface MutationStats {
  /** Rows the predicate matched. */
  matched: number
  /** Rows tombstoned (removed from the live set). */
  nTombstoned: number
  /** Matched rows that were not found in any live segment. */
  nNotFound: number
}
/**
 * Text-predicate filter for `vectorSearch` — a pushdown pre-filter, not a
 * post-filter: kNN ranks only among rows whose FTS-indexed `column` matches
 * `query`. `mode` is `"or"` (default) or `"and"`.
 */
export interface VectorFilter {
  /** FTS-indexed column the predicate applies to. */
  column: string
  /** Query terms, tokenized by the index tokenizer. */
  query: string
  /** Token matching mode: `"or"` (default) or `"and"`. */
  mode?: string
}
/**
 * Open (or create) a catalog rooted at `uri` (local dir, `memory://`, or
 * object-store prefix). S3-compatible static credentials are passed via
 * `options` (the JS-idiomatic form of the Rust `ConnectOptions`).
 */
export declare function connect(uri: string, options?: ConnectOptions | undefined | null): Connection
/**
 * Infino's build identifier (version + build hash) from the core crate.
 * Re-exported on the JS side as the `BUILDER_ID` string constant.
 */
export declare function builderId(): string
/**
 * Declares which columns are full-text (BM25) and which are vector (IVF
 * kNN) indexed. Built fluently:
 * `new IndexSpec().fts("body").vector("emb", 384, 256, "cosine")`.
 */
export declare class IndexSpec {
  constructor()
  /** Mark `column` (a UTF-8 string column) as full-text indexed. */
  fts(column: string): IndexSpec
  /**
   * Mark `column` (a `fixed_size_list<float32, dim>`) as vector
   * indexed. `nCent` is the IVF centroid count (size it to the table's
   * scale); `metric` is `"cosine"` / `"l2sq"` / `"negdot"`.
   */
  vector(column: string, dim: number, nCent: number, metric: string): IndexSpec
}
/** A catalog connection. `const db = connect(uri)`. */
export declare class Connection {
  /**
   * Create a table from an Arrow `Schema` (sent as an IPC `Buffer` —
   * an empty `apache-arrow` table built with the schema) and an
   * `IndexSpec`.
   */
  createTable(name: string, schema: Buffer, indexes: IndexSpec): Table
  /** Open an existing table by name. */
  openTable(name: string): Table
  /** Drop (unregister) a table. */
  dropTable(name: string, purge?: boolean | undefined | null): void
  /** List the catalog's table names. */
  listTables(): Array<string>
  /**
   * Run SQL across the catalog's tables; returns an Arrow IPC `Buffer`
   * the JS side reads with `tableFromIPC`. Search is available in SQL
   * via the TVFs, e.g.
   * `SELECT _id, score FROM bm25_search('docs', 'body', 'q', 10)`.
   */
  querySql(sql: string): Buffer
}
/** A single-table handle. */
export declare class Table {
  /**
   * Append data, sent as an Arrow IPC `Buffer` (`tableToIPC` on the JS
   * side). Durable when this returns — one `append` == one commit ==
   * one sealed segment, so batch rows per call. Multi-batch streams are
   * concatenated into one commit; an empty stream is a no-op.
   */
  append(data: Buffer): void
  /**
   * BM25 search over one FTS column. Returns matching rows as an Arrow
   * IPC `Buffer` (read with `tableFromIPC`). `mode` is `"or"` (default)
   * or `"and"`. `projection` selects the returned columns — pass
   * `["_id", "score"]` for just id + score, or omit for full rows.
   */
  bm25Search(column: string, query: string, k: number, mode?: string | undefined | null, projection?: Array<string> | undefined | null): Buffer
  /**
   * Vector kNN over one vector column. `query` is a `Float32Array`
   * (crosses by reference — no copy). Returns matching rows as an Arrow
   * IPC `Buffer` (read with `tableFromIPC`). `projection` selects the
   * returned columns (`["_id", "score"]` for just id + score, or omit
   * for full rows).
   */
  vectorSearch(column: string, query: Float32Array, k: number, nprobe?: number | undefined | null, rerankMult?: number | undefined | null, projection?: Array<string> | undefined | null, filter?: VectorFilter | undefined | null): Buffer
  /**
   * Unranked token match over one FTS column — every row whose `column`
   * matches the query's tokens under `mode` (`"or"` default, `"and"`).
   * Returns Arrow rows like [`Table::bm25_search`], with `score` = 0.0.
   * `projection` selects columns (omit for full rows).
   */
  tokenMatch(column: string, query: string, mode?: string | undefined | null, projection?: Array<string> | undefined | null): Buffer
  /**
   * Unranked exact match of `value` against `column`. Returns Arrow rows
   * like [`Table::bm25_search`], with `score` = 0.0. `projection` selects
   * columns (omit for full rows).
   */
  exactMatch(column: string, value: string, projection?: Array<string> | undefined | null): Buffer
  /**
   * Delete every row matching a SQL `predicate` (e.g. `"status = 'spam'"`),
   * returning the mutation counts. Requires durable storage — a `memory://`
   * table surfaces a clear error.
   */
  delete(predicate: string): MutationStats
  /**
   * Replace every row matching a SQL `predicate` with `rows` (an Arrow IPC
   * `Buffer`, like `append`), 1:1 — the matched count must equal the
   * replacement-row count or the engine errors. Requires durable storage.
   */
  update(predicate: string, rows: Buffer): MutationStats
  /**
   * Merge small / underfilled superfiles into larger ones. `settings` tunes
   * the memory budget, fill threshold, and target size (omit for engine
   * defaults).
   */
  optimize(settings?: OptimizeOptions | undefined | null): void
  /**
   * The user-facing Arrow schema, as an Arrow IPC `Buffer` (an empty
   * table carrying the schema; read with `tableFromIPC`).
   */
  schema(): Buffer
}
